##---
# Source: anchore-engine/templates/core_deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "anchore-engine-anchore-engine-core"
  labels:
    app: "anchore-engine-anchore-engine"
    component: core
    chart: "anchore-engine-0.2.1"
    release: "anchore-engine"
    heritage: "Tiller"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "anchore-engine-anchore-engine"
        component: core
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: anchore-engine-anchore-engine-core
      containers:
      - name: anchore-engine-core
        image: docker.io/anchore/anchore-engine:v0.2.4
        imagePullPolicy: 
        ports:
        - containerPort: 8228
          name: external-api
        - containerPort: 8083
          name: queue-service
        - containerPort: 8338
          name: webhook-service
        - containerPort: 8082
          name: catalog
        - containerPort: 8087
          name: policy-engine
        env:
        - name: ANCHORE_DB
          value: anchore
        - name: ANCHORE_DB_HOST
          value: anchore-engine-postgresql
        - name: ANCHORE_IO_USER
          valueFrom:
            secretKeyRef:
              name: anchore-engine-anchore-engine
              key: anchoreIOUser
        - name: ANCHORE_IO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: anchore-engine-anchore-engine
              key: anchoreIOPassword
        - name: ANCHORE_DB_USER
          valueFrom:
            secretKeyRef:
              name: anchore-engine-anchore-engine
              key: dbUser
        - name: ANCHORE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: anchore-engine-anchore-engine
              key: dbPassword
        - name: ANCHORE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: anchore-engine-anchore-engine
              key: adminPassword
        - name: ANCHORE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ANCHORE_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ANCHORE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: config-volume
          mountPath: /config
        readinessProbe:
          httpGet:
            path: /health
            port: external-api
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /health
            port: external-api
          timeoutSeconds: 10
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 10
        resources:
          null
          
