##---
# Source: anchore-engine/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: anchore-engine-anchore-engine
  labels:
    app: anchore-engine-anchore-engine
    chart: anchore-engine-0.2.1
    release: anchore-engine
    heritage: Tiller
    component: core
spec:
  type: ClusterIP
  ports:
    - name: anchore-external-api
      port: 8228
      targetPort: 8228
      protocol: TCP
    - name: anchore-kubewebhook
      port: 8338
      targetPort: 8338
      protocol: TCP
    - name: anchore-queue
      port: 8083
      targetPort: 8083
      protocol: TCP
    - name: anchore-catalog
      port: 8082
      targetPort: 8082
      protocol: TCP
    - name: anchore-policy
      port: 8087
      targetPort: 8087
      protocol: TCP
  selector:
    app: anchore-engine-anchore-engine
    component: core
