##---
# Source: anchore-engine/templates/worker_deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "anchore-engine-anchore-engine-worker"
  labels:
    app: "anchore-engine-anchore-engine-worker"
    chart: "anchore-engine-0.2.1"
    release: "anchore-engine"
    heritage: "Tiller"
    component: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "anchore-engine-anchore-engine-worker"
        component: worker
    spec:
      containers:
      - name: anchore-engine-worker
        image: docker.io/anchore/anchore-engine:v0.2.4
        env:
        - name: ANCHORE_ENGINE_SERVICES
          value: anchore-worker
        - name: ANCHORE_DB
          value: anchore
        - name: ANCHORE_DB_HOST
          value: anchore-engine-postgresql
        - name: ANCHORE_DB_USER
          valueFrom:
            secretKeyRef:
              name: anchore-engine-anchore-engine
              key: dbUser
        - name: ANCHORE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: anchore-engine-anchore-engine
              key: dbPassword
        - name: ANCHORE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: anchore-engine-anchore-engine
              key: adminPassword
        - name: ANCHORE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ANCHORE_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ANCHORE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: analyzer-api
          containerPort: 8084
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: analysis-scratch
          mountPath: /tmp
        livenessProbe:
          exec:
            command:
            - pgrep
            - twistd
          initialDelaySeconds: 10
          periodSeconds: 60
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: analyzer-api
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        resources:
          null
          
      volumes:
        - name: config-volume
          configMap:
            name: anchore-engine-anchore-engine-worker
        - name: analysis-scratch
          emptyDir: {}

