##---
# Source: anchore-engine/charts/postgresql/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: anchore-engine-postgresql
  labels:
    app: postgresql
    chart: postgresql-0.18.0
    release: anchore-engine
    heritage: Tiller
data:
