##---
# Source: anchore-engine/charts/postgresql/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: anchore-engine-postgresql
  labels:
    app: postgresql
    chart: postgresql-0.18.1
    release: anchore-engine
    heritage: Tiller
  annotations:
    "helm.sh/resource-policy": 
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"